What does one need to do to use a module?
> the module needs to be imported into local code-base

Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.
> random module 
    > import random 
    > lunch_idea = ("Taco Bell", "McDonalds", "In and Out", "Wendy's")
    > print("what to eat for lunch", random.choice(lunch_idea))

What is a benefit of using Exception handling?
> exception handling can you let you try a code without getting an error and avoid program crashing.

NumPy arrays are like what Python data type?
> lists.

What is one of the main benefits of using NumPy arrays.
> Numpy arrays occupy less memory.

What is one of the main requirements about the 'dtype' of NumPy arrays?
> elements are all the same. 

Of the 10 uses of NumPy, name 2.
> Mathermatical operations,  copying & viewing arrays

Name one of the other libraries we'll use with NumPy?
> pandas

What is the shape of NumPy arrays?
> tuple of non-negative integers that specify the dimensions, length and size of each array (2.4.5)

What is a Tensor?
> Tensor is an array with 3+ dimensions.

Name a reason why it's better using NumPy for Data Analysis than using a Python List?
> Numpy is more convenient. 

When creating an "empty" array, where do the elements come from?
> elements are random and depends on the state of the memory.

In [27]:
#Use the DateTime module to get Current Date and Time, and save it to a variable. Then extract just the Full month name form that variable.
# 
# 
#
import datetime as dt 

today = dt.datetime.today()

print("current month is", today)

month_name = today.strftime("%B")

print(month_name)




#Write a simple function that takes 2 parameters -- a first name and a day name.
#Set a default value for the day name of Sunday.
#Have the function print out a greeting -- using the parameters -- that says something like "Hi first-name! Happy day-name!". Remember to use the variables in the greeting to replace first-name and day-name.
#
# 
#      
def name_fun(fname,dname = "Sunday"):
    print(f"Hi {fname}! Happy {dname}!")


name_fun(fname = "Arash", dname = "Monday" )        #Invoke this function with 2 variables.


name_fun(fname = "Amrit" )      #Invoke this function with 1 variable only.


#Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). You can use the reshape method -- .reshape()
#
#
# 
import numpy as np 

list_of_elements = np.arange(12).reshape(2,3,2)

print(list_of_elements)


#Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

linear_array = np.linspace(0,20, num = 6 )

print(linear_array)

#Make a Deep Copy of the above array you created.()

import copy

new_array = copy.deepcopy(linear_array)

print ("This is a deep copy of linear_array \n", new_array)


#What are 2 reasons we use NumPy arrays over Python Lists
#
# 
def two_reason(reason1, reason2):
    print(f"Reason 1 why we use Numpy array over list is {reason1}, reason 2 is {reason2}.")

two_reason(reason1 = "Less memory", reason2 = "Convenience")




current month is 2023-02-19 17:49:43.770191
February
Hi Arash! Happy Monday!
Hi Amrit! Happy Sunday!
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[ 0.  4.  8. 12. 16. 20.]
This is a deep copy of linear_array 
 [ 0.  4.  8. 12. 16. 20.]
Reason 1 why we use Numpy array over list is Less memory, reason 2 is Convenience.
