> What does Pandas stand for?
    Panel Data Analytics 

> What are the 2 collections used in Pandas?
    Series and Dataframes

> Name 4 things Pandas can do for us.
    Data cleaning, Data filling, Data visualization, and Data inspection. 

> To permanently sort a DataFrame, which keyword should one use with the df.sort() method?
    inplace = True

> What is a CSV
    Comma separated files

> When cleaning data what values do we not like in our data?
    NULL values

In [9]:
#Concatenate these 3 arrays into a new array named 'newArray'...
        #([[25, 16]])
        #([[11, 2], [13, 4]])
        #([[7, 81], [5, 6], [11, 12]])


import numpy as np

arr_1 = np.array([[25, 16]])
arr_2 = np.array([[11, 2], [13, 4]])
arr_3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arr_1, arr_2, arr_3), axis = 0)

print("This is a concatenation of arr_1, arr_2 and arr_3\n", newArray)


#Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)

print("\nThis is sorted array\n", sortedArray)

#Reshape the 'sortedArray' array, into a new array called 'reshapedArray', so it has 2 dimensions with a size of 2, 3.

reshapedArray = sortedArray.reshape(2, 2, 3)

print("\nThis is reshaped array\n", reshapedArray)

#Unpack the array tuples from the above 'reshapedArray' into 4 well named variables. Print the 4 variables.

reshapedArray_2 = reshapedArray.reshape(4,3)

var_1 , var_2 , var_3 , var_4 = reshapedArray_2

print("\nThis is Varible 1 \n", var_1 )
print("\nThis is Varible 2\n", var_2 )
print("\nThis is Varible 3\n", var_3 )
print("\nThis is Varible 4\n", var_4 )





This is a concatenation of arr_1, arr_2 and arr_3
 [[25 16]
 [11  2]
 [13  4]
 [ 7 81]
 [ 5  6]
 [11 12]]

This is sorted array
 [[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]

This is reshaped array
 [[[16 25  2]
  [11  4 13]]

 [[ 7 81  5]
  [ 6 11 12]]]

This is Varible 1 
 [16 25  2]

This is Varible 2
 [11  4 13]

This is Varible 3
 [ 7 81  5]

This is Varible 4
 [ 6 11 12]


In [ ]:
#Combined and sort the following arrays into one called 'comboArray' ...

    #one = ([10, 11, 12, 13, 14, 15, 16, 17])
    #two = ([20, 21, 22, 23, 24, 25, 26, 27])
    #three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

import numpy as np

one = np.array([10, 11, 12, 13, 14, 15, 16, 17])
two = np.array([20, 21, 22, 23, 24, 25, 26, 27])
three = np.array([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.concatenate((one, two, three))

comboArray = np.sort(comboArray)

print("\n This is combo Array...\n", comboArray)

#Take 'comboArray' and perform the following slicing activities:
#print sec1 - the 2nd element

sec1 = comboArray[1]

print("\nthe 2nd element\n",sec1)

#print sec2 - all elements from the 3rd element to the last

sec2 = comboArray[2:]

print("\nall elements from the 3rd element to the last\n", sec2)

#print sec3 - all elements from the 4th to the 14th elements

sec3 = comboArray[3:14]

print("\nall elements from the 4th to the 14th elements\n", sec3)


#print sec4 - the last 6 elements

sec4 = comboArray[-6:]

print("\nlast 6 elements\n", sec4)

#print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.

sec5 = comboArray[:-10]

print("\nall element from #0 up to and including #15\n", sec5)


#print sec6 - from #20 every even element to the end

sec6 = comboArray[16::2]

print("\n#20 every even element to the end\n", sec6)

#print sec7 - from the last element moving forward, every 5th element.

sec7 = comboArray[-1::-5]

print("\nfrom the last element moving forward, every 5th element\n", sec7)


In [7]:
#Using simple math operations, broadcast the addition (+), division (/), and multiplication (*) operations for these 2 arrays --
    #([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        #[[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        #[[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

    #([[17.0, 70.0, 10.7]])

import numpy as np

array_1 = np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

array_2 = np.array([[17.0, 70.0, 10.7]])

array_addition = np.add(array_1, array_2)

print("\n Added Array... \n", array_addition)

array_division = np.divide(array_1, array_2)

print("\n Divided Array... \n", array_division)

array_multipication = np.multiply(array_1, array_2)

print("\n Multiplied Array... \n", array_multipication)

#Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in pont #7.

subtracted_array = np.subtract(array_1, array_2)

print("\n Subtracted Array... \n", subtracted_array)

#Using modulo find all elements that are divisible by 3 from the multi-dimensional array under point #7 above.

modulo_array = array_1[array_1 % 3 == 0]

print("\nmodulo_array... \n ", modulo_array)





 Added Array... 
 [[[ 17.    70.    10.8 ]
  [ 27.    80.3   20.71]]

 [[ 37.    90.02  30.8 ]
  [ 47.   101.    41.  ]]

 [[ 57.4   94.    50.7 ]
  [ 32.    85.5   36.2 ]]]

 Divided Array... 
 [[[0.         0.         0.00934579]
  [0.58823529 0.14714286 0.93551402]]

 [[1.17647059 0.286      1.87850467]
  [1.76470588 0.44285714 2.8317757 ]]

 [[2.37647059 0.34285714 3.73831776]
  [0.88235294 0.22142857 2.38317757]]]

 Multiplied Array... 
 [[[0.00000e+00 0.00000e+00 1.07000e+00]
  [1.70000e+02 7.21000e+02 1.07107e+02]]

 [[3.40000e+02 1.40140e+03 2.15070e+02]
  [5.10000e+02 2.17000e+03 3.24210e+02]]

 [[6.86800e+02 1.68000e+03 4.28000e+02]
  [2.55000e+02 1.08500e+03 2.72850e+02]]]

 Subtracted Array... 
 [[[-17.   -70.   -10.6 ]
  [ -7.   -59.7   -0.69]]

 [[  3.   -49.98   9.4 ]
  [ 13.   -39.    19.6 ]]

 [[ 23.4  -46.    29.3 ]
  [ -2.   -54.5   14.8 ]]]

modulo_array... 
  [ 0.  0. 30. 24. 15.]


In [ ]:
#Using Series, create a DataFrame that looks like this:

#Ingredients	Quantity	Unit
#Flour	4	cups
#Milk	1	cup
#Eggs	2	large
#Spam	1	can
#Name: Dinner, dtype: object

import pandas as pd 

Data_set_1 = {
    'Ingredients' : ["Flour", "Milk", "Eggs", "Spam"], 
    'Quantity' : [4, 1, 2, 1],
    'Unit' : ["cups", "cup", "large", "can"]}

Dinner = pd.DataFrame(Data_set_1)

print("\n Dinner data set... \n", Dinner)




#Take this data and create a DataFrame named studentData
    #{'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        #'Height': [5.1, 6.2, 5.1, 5.2],
        #'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        #'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        #'Age': [21, 23, 24, 21],
        #'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        #'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}

Data_set_2 = {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
        'Height': [5.1, 6.2, 5.1, 5.2],
        'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
        'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
        'Age': [21, 23, 24, 21],
        'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
        'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']}

studentData = pd.DataFrame(Data_set_2)

print("\n", studentData)

#Add a new column to the DataFrame with the following deserts: ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

deserts = ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

studentData['Desert'] = deserts

print("\n student data with added Deserts column... \n", studentData)

#Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by = ['Name', 'address'], inplace = True )

print("\n Student data sorted by 'name' and 'address'... \n", studentData)

In [78]:
#Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:

    #df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df.to_csv('cows_and_goats.csv')

df = pd.read_csv('cows_and_goats.csv')

print(df)


#(A) Using Pandas, make your own .CSV file with data on vegetables and save it. 

Vegetables_data = pd.DataFrame({
        'Name' : ["Carrot", "Eggplant", "Peas", "Corn"],
        'Color' : ["Orange", "Pink", "Green", "Yellow"]      
})

Vegetables_data.to_csv('Vegetables', index= False)

#(B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

df = pd.read_csv('Vegetables')

print(df)

corrected_vegetables = df.replace(to_replace=['Pink'], value= "Purple")

corrected_vegetables.to_csv('Vegetables_2')

print(corrected_vegetables)

  Unnamed: 0  Cows  Goats
0     Year 1    12     22
1     Year 2    20     19
       Name   Color
0    Carrot  Orange
1  Eggplant    Pink
2      Peas   Green
3      Corn  Yellow
       Name   Color
0    Carrot  Orange
1  Eggplant  Purple
2      Peas   Green
3      Corn  Yellow
